# Generated by Django 2.0.6 on 2021-10-08 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('pk_computadora', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('uso', models.CharField(default='0', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('pk_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=50)),
                ('fk_computadora', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CRUD.Computador')),
            ],
        ),
    ]
