# Generated by Django 2.0.6 on 2021-10-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fk_computadora',
        ),
        migrations.AddField(
            model_name='empleado',
            name='computadora',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
    ]
