# Generated by Django 2.0.6 on 2021-10-08 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computador',
            old_name='año',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='computador',
            name='codigo',
        ),
    ]
