# Generated by Django 2.0.6 on 2021-10-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_auto_20211007_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='computador',
            name='uso',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
